# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ac135bc03795a1330c03fee48312c4cb49080171d55756b5b45bee6260aea3d6c5376dd6c5d8365f553f3eb464a1dd58d6b1374a83900df4b4135233a526517

test:
  secret_key_base: 4df0259aaf607720eda74ced83bef299220611480ee4fa1de8290243f552ddeef31c1be11ba2a46fc879112d0566e80047cf91adaef1d86fdfa68b0f60b1c584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
